
DELETE FROM PRODUTO WHERE Cd_Produto=1001;

INSERT INTO PRODUTO 
VALUES (1001,'DESCRIÇÃO',25,25);

BEGIN TRANSACTION; 
    UPDATE PRODUTO SET DS_Descricao='DESCRIÇÃO 2' WHERE Cd_Produto=1001;
ROLLBACK;

SELECT * from PRODUTO WHERE Cd_Produto=1001;

BEGIN TRANSACTION; 
    UPDATE PRODUTO SET DS_Descricao='DESCRIÇÃO 3' WHERE Cd_Produto=1001;
COMMIT;

SELECT * from PRODUTO WHERE Cd_Produto=1001;